export const soderberghProjects = [
  "sex, lies, and videotape",
  "kafka",
  "king of the hill",
  "the underneath",
  "schizopolis",
  "gray's anatomy",
  "nightwatch",
  "out of sight",
  "the limey",
  "erin brockovich",
  "traffic",
  "ocean's eleven",
  "full frontal",
  "solaris",
  "eros",
  "ocean's twelve",
  "criminal",
  "bubble",
  "the good german",
  "building no. 7",
  "ocean's thirteen",
  "che",
  "the girlfriend experience",
  "the informant!",
  "and everything is going fine",
  "contagion",
  "haywire",
  "magic mike",
  "side effects",
  "logan lucky",
  "unsane",
  "high flying bird",
  "the laundromat",
  "unscripted",
  "behind the candelabra",
  "red oaks",
  "the knick",
  "godless",
  "mosaic",
  "suture",
  "the daytrippers",
  "pleasantville",
  "who is bernard tapie?",
  "tribute",
  "confessions of a dangerous mind",
  "insomnia",
  "welcome to collinwood",
  "naqoyqatsi",
  "able edwards",
  "keane",
  "symbiopsychotaxiplasm: take 2 1/2",
  "the big empty",
  "syriana",
  "good night, and good luck",
  "the jacket",
  "rumor has it...",
  "pu-239",
  "i'm not there",
  "michael clayton",
  "wind chill",
  "roman polanski: wanted and desired",
  "playground",
  "solitary man",
  "rebecca h. (return to the dogs)",
  "we need to talk about kevin",
  "his way",
  "roman polanski: odd man out",
  "citizenfour",
  "da sweet blood of jesus",
  "ocean's 8",
  "the report",
  "magic mike xxl",
  "the library",
  "the _______ report",
  "bitter pill"
];

export default {
  soderberghProjects
}
